
# This file is used to configure your Supabase project.
# It's very minimal at the moment and uses default values.
# For full list of options, see the documentation: https://supabase.com/docs/guides/hosting/overview

project_id = "hgpplvegqlvxwszlhzwc"

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.beta-signup]
verify_jwt = false
